name: CI Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: true
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Validate sources
        run: |
          npm ci
          npm run eslint
      - name: Create XPI package
        run: ./build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Extension Package
          path: build/*.xpi